export const users = {
    bixiongl: 'Bixiong Li',
    cany: 'Can Yao',
    chenc: 'Chen Cai',
    chenr: 'Chen Ran',
    chengx: 'Cheng Xie',
    haor: 'Hao Rong',
    hongfeiw: 'Hongfei Wu',
    hongli: 'Hong Li',
    hongyum: 'Hongyu Ma',
    huafangj: 'Huafang Ji',
    huihaol: 'Huihao Liao',
    jingyic: 'Jingyi Chen',
    kesil: 'Kesi Lu',
    kewa: 'Lisa Wang',
    leix: 'Lei Xu',
    lingl: 'Ling Liu',
    manny: 'Mann Yuan',
    maoz: 'Mao Zhang',
    pengpengf: 'Pengpeng Fan',
    weilo: 'Peter Long',
    qiangh: 'Qiang Huang',
    qiangxu: 'Qiang Xu',
    ruiz: 'Rui Zhu',
    shuaiz: 'Shuai Zhang',
    simonzh: 'Simon Zhang',
    wenchaol: 'Wenchao Li',
    wenhuip: 'Wenhui Peng',
    wenxic: 'Wenxi Chen',
    xiaodongh: 'Xiaodong Huang',
    xinl: 'Xin Liang',
    yongyuc: 'Yongyu Chen',
    yuanyuanz: 'Yuanyuan Zhang',
    zhenm: 'Zhen Ma',
    zhibinw: 'Zhibin Wang',
    zongmingz: 'Zongming Zhang',
    't_jiex': 'Jie Xu (3P)',
    't_ranw': 'Ran Wang (3P)',
    't_qingbeix': 'Qingbei Xue (3P)',
};
